# Generated by Django 4.2.15 on 2024-09-13 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_cards_detailed_desc_netbanking_pessanger_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 9, 13, 13, 8, 53, 998279, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
