# Generated by Django 4.2.15 on 2024-09-13 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day4',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day5',
        ),
        migrations.RemoveField(
            model_name='detailed_desc',
            name='day6',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 9, 13, 17, 20, 41, 997069, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('detailed_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_descriptions', to='travello.detailed_desc')),
            ],
        ),
    ]
