# Generated by Django 4.2.15 on 2024-10-10 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_contactus_alter_transactions_date_time_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 10, 10, 14, 21, 10, 714191, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
