# Generated by Django 4.2.15 on 2024-10-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_alter_transactions_date_time_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 10, 10, 16, 1, 37, 417352, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
