# Generated by Django 4.2.16 on 2024-10-30 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_alter_transactions_date_time_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 10, 30, 10, 52, 5, 678160, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.detailed_desc'),
        ),
    ]
