# Generated by Django 4.2.16 on 2024-10-30 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_alter_transactions_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 10, 30, 10, 55, 25, 659467, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
