# Generated by Django 4.2.16 on 2024-11-01 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 5, 43, 45, 645860, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
