# Generated by Django 4.2.16 on 2024-11-02 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_city_alter_transactions_date_time_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 2, 10, 35, 54, 453110, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travello.detailed_desc'),
        ),
    ]
