# Generated by Django 4.2.16 on 2024-11-02 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0014_alter_transactions_date_time_alter_trip_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='dest_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 2, 10, 50, 1, 486811, tzinfo=datetime.timezone.utc), max_length=19),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travello.detailed_desc', to_field='dest_name'),
        ),
    ]
