# Generated by Django 4.2.15 on 2024-09-02 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 9, 2, 8, 44, 41, 633430, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
