# Generated by Django 4.2.15 on 2024-09-11 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 9, 11, 10, 54, 35, 656740, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
