# Generated by Django 4.2.16 on 2024-11-02 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailed_desc',
            name='country',
        ),
        migrations.AddField(
            model_name='detailed_desc',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='travello.destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 2, 11, 1, 0, 114847, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
