# Generated by Django 4.2.16 on 2024-11-02 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_remove_detailed_desc_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 2, 11, 1, 11, 250410, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
