# Generated by Django 4.2.16 on 2024-11-02 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailed_desc',
            old_name='destination',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 2, 11, 8, 40, 444606, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
