# Generated by Django 4.2.16 on 2024-11-04 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0021_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 4, 3, 53, 6, 374699, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
