# Generated by Django 4.2.16 on 2024-11-13 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0023_dummycreditcard_mockpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='travello.detailed_desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.city'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 13, 4, 58, 26, 423511, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
