# Generated by Django 4.2.16 on 2024-11-13 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0026_alter_passengerdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 11, 13, 12, 30, 31, 672385, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
